<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="shhinduj-p51" name="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests" tests="11" failures="3" timestamp="24 Apr 2019 07:06:08 GMT" time="178.523" errors="0">
  <testcase name="ta_71" time="6.549" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests"/>
  <testcase name="ta_71" time="39.024" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests"/>
  <testcase name="ta_71" time="6.207" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests"/>
  <testcase name="ta_72" time="7.141" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests"/>
  <testcase name="ta_72" time="6.784" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests"/>
  <testcase name="ta_72" time="5.411" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests"/>
  <testcase name="tc_73" time="15.807" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests"/>
  <testcase name="tc_74" time="25.543" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests">
    <failure type="java.lang.AssertionError" message=".bat Zip file uploaded">
      <![CDATA[java.lang.AssertionError: .bat Zip file uploadedat org.testng.Assert.fail(Assert.java:96)at org.tibco.automation.common.testcases.tsc_navbar.Support_Tests.tc_74(Support_Tests.java:99)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- tc_74 -->
  <testcase name="tc_75" time="15.043" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests"/>
  <testcase name="tc_76" time="25.540" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests">
    <failure type="java.lang.AssertionError" message=".exe Zip file uploaded">
      <![CDATA[java.lang.AssertionError: .exe Zip file uploadedat org.testng.Assert.fail(Assert.java:96)at org.tibco.automation.common.testcases.tsc_navbar.Support_Tests.tc_76(Support_Tests.java:133)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- tc_76 -->
  <testcase name="tc_77" time="25.474" classname="org.tibco.automation.common.testcases.tsc_navbar.Support_Tests">
    <failure type="java.lang.AssertionError" message=" Zip file uploaded">
      <![CDATA[java.lang.AssertionError:  Zip file uploadedat org.testng.Assert.fail(Assert.java:96)at org.tibco.automation.common.testcases.tsc_navbar.Support_Tests.tc_77(Support_Tests.java:150)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- tc_77 -->
</testsuite> <!-- org.tibco.automation.common.testcases.tsc_navbar.Support_Tests -->
